
permalink:        /:categories/:title.html

paginate:         10

pygments:         true
markdown:         kramdown

exclude: ['README.md', "Rakefile", 'sass/']


title:            BioRecorder


# Website url address.
# It must be a valid url.
# This means always setting the protocol (http|https) or prefixing with "/"
url:        http://biorecorder.com/

#   - When in localhost, the site will run from root "/" regardless of url
#   - Only the following values are falsy: ["", null, false]
localhost:  true


# Base folder to store images.
# In website we can use it to indicate image src: <img src="{{ site.img }}/img-name" >
#
# In YAML blok  liquid variables cant be used so there we write just img-name
#
# ---
# header_img: img-name
# ---
#
# and it will be converted then to {{site.img}}/img-name
img:      /assets/images

# Base folder to store css files.
css:         /stylesheets

# Base folder to store javascript files.
js:  /assets/javascript



description:  "Wireless 8 channels biopotential measurement system"

